### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by norangi** [norangi/api-checker#1]
- [ ] Make sure that **real** response contains what's in expected response
- [ ] Flag some things that **real** doesn't contain
- [ ] Flag some things that **real** contains more

**Comment by norangi** [comment]
- [ ] **Recursively** find keys inside the **expected** and see what's missing.

**Comment by norangi** [comment]
- [ ] Move the res to one JSON and reference that JSON file?

**Comment by norangi** [comment]
- [ ] Enable POST/ DELETE/ PATCH?

**Comment by norangi** [comment]
<img width="375" alt="screen shot 2018-06-18 at 10 26 38 pm" src="https://user-images.githubusercontent.com/36755736/41576045-38770c3e-7353-11e8-91b8-6d85302c5b14.png">
